/**
 * Bollywood Songs Playlist
 * Curated for the Indian Delivery Boys web app
 */

const SONGS = [
  // 90s Classics (30+ songs)
  { id: 1, title: 'Tujhe Dekha Toh Yeh Jaana Sanam', artist: 'Kumar Sanu, Lata Mangeshkar', movie: 'DDLJ', year: 1995, youtubeId: 'cNV5hLSa9H8' },
  { id: 2, title: 'Pehla Nasha', artist: 'Udit Narayan', movie: 'Jo Jeeta Wohi Sikandar', year: 1992, youtubeId: '8p1oDqQJ7YI' },
  { id: 3, title: 'Chaiyya Chaiyya', artist: 'Sukhwinder Singh', movie: 'Dil Se', year: 1998, youtubeId: 'PQmrmVs10X8' },
  { id: 4, title: 'Kuch Kuch Hota Hai', artist: 'Udit Narayan, Alka Yagnik', movie: 'KKHH', year: 1998, youtubeId: '0KGx1hxqcwE' },
  { id: 5, title: 'Ek Ladki Ko Dekha', artist: 'Kumar Sanu', movie: '1942: A Love Story', year: 1994, youtubeId: 'E2wz5eM9vBE' },
  { id: 6, title: 'Dil To Pagal Hai', artist: 'Lata Mangeshkar, Udit Narayan', movie: 'Dil To Pagal Hai', year: 1997, youtubeId: 'G1wM5A-nZp4' },
  { id: 7, title: 'Jaadu Teri Nazar', artist: 'Udit Narayan', movie: 'Darr', year: 1993, youtubeId: 'w2s1IrtX_zQ' },
  { id: 8, title: 'Ye Kaali Kaali Aankhen', artist: 'Kumar Sanu', movie: 'Baazigar', year: 1993, youtubeId: 'v8yIip_E39A' },
  { id: 9, title: 'Tu Mile Dil Khile', artist: 'Kumar Sanu', movie: 'Criminal', year: 1994, youtubeId: 'oT2r6Xz4zZg' },
  { id: 10, title: 'Mere Sapno Ki Rani', artist: 'Kishore Kumar', movie: 'Aradhana', year: 1969, youtubeId: 'u4Y403XlH8s' },
  { id: 11, title: 'Papa Kehte Hain', artist: 'Udit Narayan', movie: 'QSQT', year: 1988, youtubeId: 'wR3H7A19lEw' },
  { id: 12, title: 'Ae Mere Humsafar', artist: 'Udit Narayan, Alka Yagnik', movie: 'QSQT', year: 1988, youtubeId: 'qQ244N1s1b0' },
  { id: 13, title: 'Dil Hai Ki Manta Nahin', artist: 'Kumar Sanu, Anuradha Paudwal', movie: 'Dil Hai Ki Manta Nahin', year: 1991, youtubeId: 'R9eF1N_O0eE' },
  { id: 14, title: 'Dekha Hai Pehli Baar', artist: 'Kumar Sanu', movie: 'Saajan', year: 1991, youtubeId: 'k4wV6L8nN4k' },
  { id: 15, title: 'Mera Dil Bhi Kitna Pagal Hai', artist: 'Kumar Sanu, Alka Yagnik', movie: 'Saajan', year: 1991, youtubeId: 'Dq6_M0y1C8g' },
  { id: 16, title: 'Tip Tip Barsa Paani', artist: 'Alka Yagnik, Udit Narayan', movie: 'Mohra', year: 1994, youtubeId: 'K7oD6c3Jp4E' },
  { id: 17, title: 'Tu Cheez Badi Hai Mast Mast', artist: 'Udit Narayan', movie: 'Mohra', year: 1994, youtubeId: 'n_X9f89vFVs' },
  { id: 18, title: 'Chura Ke Dil Mera', artist: 'Kumar Sanu', movie: 'Main Khiladi Tu Anari', year: 1994, youtubeId: 'Jg6zL3t4-bY' },
  { id: 19, title: 'Sochenge Tumhe Pyar', artist: 'Kumar Sanu', movie: 'Deewana', year: 1992, youtubeId: '9G_k7pU3v4I' },
  { id: 20, title: 'Tere Naam', artist: 'Udit Narayan', movie: 'Tere Naam', year: 2003, youtubeId: '0C8rQy32U5k' },
  { id: 21, title: 'Aashiqui Mein Har Aashiq', artist: 'Kumar Sanu', movie: 'Aashiqui', year: 1990, youtubeId: 'u7_tP6B15jA' },
  { id: 22, title: 'Nazar Ke Saamne', artist: 'Kumar Sanu', movie: 'Aashiqui', year: 1990, youtubeId: 'F4v31-R2h9E' },
  { id: 23, title: 'Dheere Dheere Se', artist: 'Kumar Sanu', movie: 'Aashiqui', year: 1990, youtubeId: 'J-K13Q8B0mU' },
  { id: 24, title: 'Pehli Pehli Baar Mohabbat Ki Hai', artist: 'Kumar Sanu', movie: 'Sirf Tum', year: 1999, youtubeId: '7_zQn3l7EGo' },
  { id: 25, title: 'Main Koi Aisa Geet Gaoon', artist: 'Kumar Sanu', movie: 'Yes Boss', year: 1997, youtubeId: 'Z9R_mZzXyX0' },
  { id: 26, title: 'Chand Sifarish', artist: 'Shaan', movie: 'Fanaa', year: 2006, youtubeId: 'v8v11fKqRyk' },
  { id: 27, title: 'Taal Se Taal Mila', artist: 'A.R. Rahman', movie: 'Taal', year: 1999, youtubeId: '1kL0_jC0mQ4' },
  { id: 28, title: 'Rang De Basanti', artist: 'Daler Mehndi', movie: 'Rang De Basanti', year: 2006, youtubeId: 'UHk4z6_U5H0' },
  { id: 29, title: 'Sandese Aate Hain', artist: 'Sonu Nigam, Roop Kumar Rathod', movie: 'Border', year: 1997, youtubeId: '7Y4p7BvK8b0' },
  { id: 30, title: 'Hum Tumhare Hain Sanam', artist: 'S.P. Balasubrahmanyam', movie: 'HAHK', year: 1994, youtubeId: 'k7KxR6_0pKw' },
  { id: 31, title: 'Didi Tera Devar Deewana', artist: 'Lata Mangeshkar, S.P. Balasubrahmanyam', movie: 'HAHK', year: 1994, youtubeId: '2V56f0xBNyM' },

  // 2000s Hits (25+ songs)
  { id: 32, title: 'Kal Ho Naa Ho', artist: 'Sonu Nigam', movie: 'KHNH', year: 2003, youtubeId: 'g0eO74OmR0A' },
  { id: 33, title: 'Kajra Re', artist: 'Alisha Chinai, Shankar Mahadevan', movie: 'Bunty Aur Babli', year: 2005, youtubeId: '7vB_3tX8r1M' },
  { id: 34, title: 'Tum Se Hi', artist: 'Mohit Chauhan', movie: 'Jab We Met', year: 2007, youtubeId: 'Cb6wuzOuW1c' },
  { id: 35, title: 'Mauja Hi Mauja', artist: 'Mika Singh', movie: 'Jab We Met', year: 2007, youtubeId: '5-w07E4U-8g' },
  { id: 36, title: 'Tera Hone Laga Hoon', artist: 'Atif Aslam', movie: 'Ajab Prem Ki Ghazab Kahani', year: 2009, youtubeId: 'rTU_P2K_h94' },
  { id: 37, title: 'Dil Chahta Hai', artist: 'Shankar Mahadevan', movie: 'DCH', year: 2001, youtubeId: 'H_vK-2bE46o' },
  { id: 38, title: 'Jaane Kyun', artist: 'Zubin', movie: 'Dostana', year: 2008, youtubeId: '7N5a3sD510I' },
  { id: 39, title: 'Kya Mujhe Pyaar Hai', artist: 'KK', movie: 'Woh Lamhe', year: 2006, youtubeId: 'e4X10T7e6Z0' },
  { id: 40, title: 'Tadap Tadap', artist: 'KK', movie: 'Hum Dil De Chuke Sanam', year: 1999, youtubeId: 'oG3a_h5Y09I' },
  { id: 41, title: 'Dola Re Dola', artist: 'Kavita Krishnamurthy, Shreya Ghoshal', movie: 'Devdas', year: 2002, youtubeId: 'Jbn39j-xa-k' },
  { id: 42, title: 'Dil Se Re', artist: 'A.R. Rahman', movie: 'Dil Se', year: 1998, youtubeId: 'YwfCMGErjPM' },
  { id: 43, title: 'Zara Sa Jhoom Loon Main', artist: 'Asha Bhosle', movie: 'DDLJ', year: 1995, youtubeId: 'yF-y0zK_2A0' },
  { id: 44, title: 'Senorita', artist: 'Shankar, Loy', movie: 'Zindagi Na Milegi Dobara', year: 2011, youtubeId: '2qJt77n-qG8' },
  { id: 45, title: 'Bheegi Bheegi Raaton Mein', artist: 'Adnan Sami', movie: 'Ajnabee', year: 2001, youtubeId: 'rX7w9M0_Qp4' },
  { id: 46, title: 'Do Pal', artist: 'Lata Mangeshkar, Sonu Nigam', movie: 'Veer-Zaara', year: 2004, youtubeId: 'xP-Zg71P6bI' },
  { id: 47, title: 'Main Yahaan Hoon', artist: 'Udit Narayan', movie: 'Veer-Zaara', year: 2004, youtubeId: '1pZ1g5W3c6Y' },
  { id: 48, title: 'Phir Le Aya Dil', artist: 'Arijit Singh', movie: 'Barfi', year: 2012, youtubeId: '7L_2V5Q8BKY' },
  { id: 49, title: 'Tum Hi Ho', artist: 'Arijit Singh', movie: 'Aashiqui 2', year: 2013, youtubeId: 'Umqb9KENgmk' },
  { id: 50, title: 'Kun Faya Kun', artist: 'A.R. Rahman, Javed Ali', movie: 'Rockstar', year: 2011, youtubeId: 'T94IgFMM5QU' },
  { id: 51, title: 'Tujhe Bhula Diya', artist: 'Mohit Chauhan', movie: 'Anjaana Anjaani', year: 2010, youtubeId: 'u4Y403XlH80' },
  { id: 52, title: 'Kabhi Alvida Naa Kehna', artist: 'Sonu Nigam', movie: 'KANK', year: 2006, youtubeId: 'tK3gW7b6n8A' },
  { id: 53, title: 'Maahi Ve', artist: 'Faakhir', movie: 'Kaante', year: 2002, youtubeId: 'rT2hK29hN_w' },
  { id: 54, title: 'Kaho Naa Pyaar Hai', artist: 'Udit Narayan', movie: 'KNPH', year: 2000, youtubeId: 'G1wM5A-nZp5' },
  { id: 55, title: 'Tera Mera Rishta', artist: 'Kumar Sanu, Alka Yagnik', movie: 'Awarapan', year: 2007, youtubeId: 'v8v11fKqRy1' },

  // Modern Hits (24+ songs)
  { id: 56, title: 'Tum Hi Ho (Reprise)', artist: 'Arijit Singh', movie: 'Aashiqui 2', year: 2013, youtubeId: '8hQd3Z10Xw8' },
  { id: 57, title: 'Tera Ban Jaunga', artist: 'Akhil Sachdeva, Tulsi Kumar', movie: 'Kabir Singh', year: 2019, youtubeId: 'pU8-L2mDkHQ' },
  { id: 58, title: 'Tujhe Kitna Chahne Lage', artist: 'Arijit Singh', movie: 'Kabir Singh', year: 2019, youtubeId: 'Z-1D-bE26wE' },
  { id: 59, title: 'Dil Diyan Gallan', artist: 'Atif Aslam', movie: 'Tiger Zinda Hai', year: 2017, youtubeId: 'SAcpESN_Fk4' },
  { id: 60, title: 'Shayad', artist: 'Arijit Singh', movie: 'Love Aaj Kal', year: 2020, youtubeId: 'pZ_Yq-X9cEE' },
  { id: 61, title: 'Hawayein', artist: 'Arijit Singh', movie: 'Jab Harry Met Sejal', year: 2017, youtubeId: 'cYOB941gyXI' },
  { id: 62, title: 'Raabta', artist: 'Arijit Singh', movie: 'Agent Vinod', year: 2012, youtubeId: 'z2h-o_X9qL0' },
  { id: 63, title: 'Channa Mereya', artist: 'Arijit Singh', movie: 'ADHM', year: 2016, youtubeId: 'bzSTpdcs-EI' },
  { id: 64, title: 'Bulleya', artist: 'Amit Mishra', movie: 'ADHM', year: 2016, youtubeId: 'hXh35Cnn-Dk' },
  { id: 65, title: 'Gerua', artist: 'Arijit Singh, Antara Mitra', movie: 'Dilwale', year: 2015, youtubeId: 'AEIVhBS6baE' },
  { id: 66, title: 'Jeena Jeena', artist: 'Atif Aslam', movie: 'Badlapur', year: 2015, youtubeId: 'vKieVlK7yW0' },
  { id: 67, title: 'Soch Na Sake', artist: 'Arijit Singh, Tulsi Kumar', movie: 'Airlift', year: 2016, youtubeId: 'Oq9h4z10Xw8' },
  { id: 68, title: 'Tera Yaar Hoon Main', artist: 'Arijit Singh', movie: 'Sonu Ke Titu Ki Sweety', year: 2018, youtubeId: 'E1Z_O-5iFEY' },
  { id: 69, title: 'Ik Vaari Aa', artist: 'Arijit Singh', movie: 'Raabta', year: 2017, youtubeId: 'B_lEwXqYF9I' },
  { id: 70, title: 'Ve Maahi', artist: 'Arijit Singh, Asees Kaur', movie: 'Kesari', year: 2019, youtubeId: 'j-5H8xW-MKE' },
  { id: 71, title: 'Lut Gaye', artist: 'Jubin Nautiyal', movie: 'Single', year: 2021, youtubeId: 'sCbbMZ-q4-I' },
  { id: 72, title: 'Raataan Lambiyan', artist: 'Jubin Nautiyal, Asees Kaur', movie: 'Shershaah', year: 2021, youtubeId: 'gvyUuxdRdR4' },
  { id: 73, title: 'Mann Bharryaa', artist: 'B Praak', movie: 'Shershaah', year: 2021, youtubeId: 'tOOTqO2U9iY' },
  { id: 74, title: 'Ranjha', artist: 'B Praak', movie: 'Shershaah', year: 2021, youtubeId: 'V7LwfY5U5WI' },
  { id: 75, title: 'Kesariya', artist: 'Arijit Singh', movie: 'Brahmastra', year: 2022, youtubeId: 'BddP6PYo2gs' },
  { id: 76, title: 'Pasoori', artist: 'Ali Sethi, Shae Gill', movie: 'Coke Studio', year: 2022, youtubeId: '5Eqb_-j3FDA' },
  { id: 77, title: 'Apna Bana Le', artist: 'Arijit Singh', movie: 'Bhediya', year: 2022, youtubeId: 'ElZfdU54Cp8' },
  { id: 78, title: 'Phir Aur Kya Chahiye', artist: 'Arijit Singh', movie: 'Zara Hatke Zara Bachke', year: 2023, youtubeId: 'm4XgY6LhR4c' },
  { id: 79, title: 'O Maahi', artist: 'Arijit Singh', movie: 'Dunki', year: 2023, youtubeId: 'jVdEHTz9-r4' },
  { id: 80, title: 'Heeriye', artist: 'Jasleen Royal, Arijit Singh', movie: 'Single', year: 2023, youtubeId: 'RLzC55ai0eo' }
];

const SONG_CATEGORIES = {
  romantic: [1, 2, 4, 5, 6, 7, 9, 10, 12, 13, 14, 15, 19, 21, 22, 23, 24, 25, 26, 30, 32, 34, 36, 39, 46, 47, 49, 56, 57, 58, 59, 60, 61, 62, 63, 65, 66, 67, 68, 69, 70, 72, 74, 75, 77, 78, 79, 80],
  sad: [20, 40, 48, 51, 52, 63, 73],
  upbeat: [3, 8, 11, 17, 18, 28, 31, 33, 35, 37, 38, 41, 43, 44, 45, 50, 53, 54, 64, 71, 76],
  rain: [16, 27, 42, 45]
};
